### PR TITLE
Add support for KCP virtual workpsace

### PR DESCRIPTION
**Pull request by hongweiliu17**
1. Make integration-introller to support kcp workspace
2. Samples to use kcp workspace.
3. Update ./bin/controller-gen because the old one doesn't work when I use it.

### CODE REVIEW

**Comment by hongweiliu17** [comment]
There are failure in CI of PR, I meet error when I run 'go build' in my macbook locally
```
# github.com/kcp-dev/apimachinery/pkg/cache
../../go/pkg/mod/github.com/kcp-dev/apimachinery@v0.0.0-20220621200107-3d03cbbc3770/pkg/cache/controller.go:40:36: cannot use meta (type v1.Object) as type logicalcluster.Object in argument to logicalcluster.From:
	v1.Object does not implement logicalcluster.Object (missing GetClusterName method)
../../go/pkg/mod/github.com/kcp-dev/apimachinery@v0.0.0-20220621200107-3d03cbbc3770/pkg/cache/controller.go:50:36: cannot use meta (type v1.Object) as type logicalcluster.Object in argument to logicalcluster.From:
	v1.Object does not implement logicalcluster.Object (missing GetClusterName method)
../../go/pkg/mod/github.com/kcp-dev/apimachinery@v0.0.0-20220621200107-3d03cbbc3770/pkg/cache/controller.go:61:36: cannot use meta (type v1.Object) as type logicalcluster.Object in argument to logicalcluster.From:
	v1.Object does not implement logicalcluster.Object (missing GetClusterName method)
```

Any help are appreciated.

**Comment by hongweiliu17** [comment]
Go package should be updated `github.com/kcp-dev/logicalcluster/v2 v2.0.0-alpha.1` should replace `github.com/kcp-dev/logicalcluster v1.1.1`, `github.com/kcp-dev/apimachinery v0.0.0-20220805180221-5b13097793e1` should be used in main.go. The error disappears now.

**Review by jsztuka — APPROVED** [review]
LGTM

**Review by Dannyb48 — APPROVED** [review]
LGTM

**Comment by srivickynesh** [comment]
Note: Gosec Task failure is addressed in https://github.com/redhat-appstudio/integration-service/pull/29 PR.

**Comment by hongweiliu17** [comment]
Need to add more code because the integration controller is split to two controllers
